// Recipe book encrypt/decrypt tool.
//   npm run recipes:encrypt   recipes/recipes.json -> src/shared/ai/recipeData.ts
//   npm run recipes:decrypt   src/shared/ai/recipeData.ts -> recipes/recipes.json
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { decryptText, encryptText } from '../src/shared/ai/recipeCrypto'

const JSON_FILE = 'recipes/recipes.json'
const DATA_FILE = 'src/shared/ai/recipeData.ts'
const mode = process.argv[2]

if (mode === 'encrypt') {
  const text = readFileSync(JSON_FILE, 'utf8')
  const recipes = JSON.parse(text) // fail early on invalid JSON
  if (!Array.isArray(recipes)) throw new Error(`${JSON_FILE} must contain an array of recipes`)
  const payload = encryptText(JSON.stringify(recipes))
  writeFileSync(
    DATA_FILE,
    `// GENERATED by \`npm run recipes:encrypt\` from recipes/recipes.json — do not edit.\n` +
      `// The recipe book, encrypted (see recipeCrypto.ts).\n` +
      `export const RECIPE_DATA =\n  '${payload}'\n`
  )
  console.log(`encrypted ${recipes.length} recipes -> ${DATA_FILE}`)
} else if (mode === 'decrypt') {
  const src = readFileSync(DATA_FILE, 'utf8')
  const payload = src.match(/'([A-Za-z0-9+/=]+)'/)?.[1]
  if (!payload) throw new Error(`no encrypted data found in ${DATA_FILE}`)
  const recipes = JSON.parse(decryptText(payload))
  if (!existsSync('recipes')) mkdirSync('recipes')
  writeFileSync(JSON_FILE, JSON.stringify(recipes, null, 2) + '\n')
  console.log(`decrypted ${recipes.length} recipes -> ${JSON_FILE}`)
} else {
  console.error('usage: npm run recipes:encrypt | npm run recipes:decrypt')
  process.exit(1)
}
